name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.PATT2 }}
          owner: Grasscutters
          base: development
          head: development   
          auto_approve: true
          merge_method: merge
